services:
  weather-analytics:
    build: .
    container_name: weather-analytics
    ports:
      - "5001:5000"
    env_file:
      - .env.docker
    volumes:
      - ./instance:/app/instance
      - ./weather_analytics:/app/weather_analytics
      - ./templates:/app/templates
      - ./static:/app/static
      - ./openapi.json:/app/openapi.json
    restart: unless-stopped
